"""第三次

Revision ID: 02eca04af6b8
Revises: 1f70fd63b97b
Create Date: 2022-01-01 16:38:46.394400

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02eca04af6b8'
down_revision = '1f70fd63b97b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('t_user', sa.Column('createTime', sa.DATETIME(), nullable=True))
    op.add_column('t_user', sa.Column('updateTime', sa.DATETIME(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('t_user', 'updateTime')
    op.drop_column('t_user', 'createTime')
    # ### end Alembic commands ###
