"""第二次

Revision ID: 1f70fd63b97b
Revises: d8475e8442a1
Create Date: 2022-01-01 15:49:27.343400

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f70fd63b97b'
down_revision = 'd8475e8442a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('t_user', sa.Column('address', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('t_user', 'address')
    # ### end Alembic commands ###
