"""1/21提交

Revision ID: 20ce10d93024
Revises: 7dc55bc91f6e
Create Date: 2022-01-21 22:04:52.177200

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20ce10d93024'
down_revision = '7dc55bc91f6e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('t_goodsify',
    sa.Column('createTime', sa.DATETIME(), nullable=True),
    sa.Column('updateTime', sa.DATETIME(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('t_goodslist',
    sa.Column('createTime', sa.DATETIME(), nullable=True),
    sa.Column('updateTime', sa.DATETIME(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('parentlevel', sa.Integer(), nullable=True),
    sa.Column('goodsify_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['goodsify_id'], ['t_goodsify.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('t_goodslist')
    op.drop_table('t_goodsify')
    # ### end Alembic commands ###
