"""1/21提交

Revision ID: 838f25233543
Revises: 94565e70cb79
Create Date: 2022-01-21 23:04:28.876200

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '838f25233543'
down_revision = '94565e70cb79'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('t_goods', sa.Column('level', sa.Integer(), nullable=True))
    op.drop_column('t_goods', 'parentlevel')
    op.add_column('t_goodslist', sa.Column('level', sa.Integer(), nullable=True))
    op.drop_column('t_goodslist', 'parentlevel')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('t_goodslist', sa.Column('parentlevel', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_column('t_goodslist', 'level')
    op.add_column('t_goods', sa.Column('parentlevel', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_column('t_goods', 'level')
    # ### end Alembic commands ###
