"""1/21在提交

Revision ID: 94565e70cb79
Revises: 20ce10d93024
Create Date: 2022-01-21 22:52:52.402200

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '94565e70cb79'
down_revision = '20ce10d93024'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('t_goods',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('parentlevel', sa.Integer(), nullable=True),
    sa.Column('goodlist_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['goodlist_id'], ['t_goodslist.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.drop_column('t_goodsify', 'updateTime')
    op.drop_column('t_goodsify', 'createTime')
    op.drop_column('t_goodslist', 'updateTime')
    op.drop_column('t_goodslist', 'createTime')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('t_goodslist', sa.Column('createTime', mysql.DATETIME(), nullable=True))
    op.add_column('t_goodslist', sa.Column('updateTime', mysql.DATETIME(), nullable=True))
    op.add_column('t_goodsify', sa.Column('createTime', mysql.DATETIME(), nullable=True))
    op.add_column('t_goodsify', sa.Column('updateTime', mysql.DATETIME(), nullable=True))
    op.drop_table('t_goods')
    # ### end Alembic commands ###
