"""2/19

Revision ID: a37dcfe57dab
Revises: e31f3a30be48
Create Date: 2022-02-19 14:14:02.327750

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a37dcfe57dab'
down_revision = 'e31f3a30be48'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('t_goods', sa.Column('pirce', sa.Integer(), nullable=True))
    op.add_column('t_goods', sa.Column('repertory', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('t_goods', 'repertory')
    op.drop_column('t_goods', 'pirce')
    # ### end Alembic commands ###
