"""2/7提交

Revision ID: e31f3a30be48
Revises: e3325a1f4627
Create Date: 2022-02-07 19:54:00.510000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e31f3a30be48'
down_revision = 'e3325a1f4627'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('t_goods', sa.Column('info', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('t_goods', 'info')
    # ### end Alembic commands ###
